# Generated by Django 6.0.3 on 2026-03-19 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(choices=[('gardener', 'Gardener'), ('common_power_usage', 'Common power usage'), ('common_water_usage', 'Common water usage'), ('cleaning', 'Cleaning'), ('elevator_service', 'Elevator service'), ('gas_heating_bill', 'Gas heating bill'), ('water_consumption_bill', 'Water consumption bill'), ('damages', 'Damages'), ('annual_servicing', 'Annual servicing'), ('other', 'Other')], max_length=64)),
                ('expense_date', models.DateField()),
                ('month', models.CharField(blank=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='flats.building')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeatedWaterMeasurementInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('inputs_json', models.JSONField(blank=True, default=dict)),
                ('computed_heating_water_volume', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heated_water_inputs', to='flats.apartment')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('apartment', 'month')},
            },
        ),
        migrations.CreateModel(
            name='HeatingMeasurementInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('e_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('f_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('units_counted', models.DecimalField(decimal_places=4, max_digits=12)),
                ('computed_radiator_heating_energy', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_inputs', to='flats.apartment')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('apartment', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('heating_radiators_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('heated_water_energy_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('water_consumption_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('common_recurring_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('common_non_recurring_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='flats.apartment')),
            ],
            options={
                'unique_together': {('apartment', 'month')},
            },
        ),
    ]
