# Generated by Django 6.0.3 on 2026-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_expenseitem_heatedwatermeasurementinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='heating_e_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heating_f_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
