# Generated by Django 6.0.3 on 2026-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_apartment_heating_e_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
