# Generated by Django 6.0.3 on 2026-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_apartment_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatedwatermeasurementinput',
            name='current_reading',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='heatingmeasurementinput',
            name='current_reading',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='expense_category',
            field=models.CharField(choices=[('gardener', 'Κηπουρός'), ('common_power_usage', 'Κοινόχρηστο ρεύμα'), ('common_water_usage', 'Κοινόχρηστο νερό'), ('cleaning', 'Καθαρισμός'), ('elevator_service', 'Συντήρηση ανελκυστήρα'), ('gas_heating_bill', 'Λογαριασμός φυσικού αερίου θέρμανσης'), ('water_consumption_bill', 'Λογαριασμός κατανάλωσης νερού'), ('damages', 'Ζημιές'), ('annual_servicing', 'Ετήσια συντήρηση'), ('other', 'Λοιπά')], max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Πρόχειρο'), ('issued', 'Εκδομένο'), ('paid', 'Εξοφλημένο')], default='draft', max_length=16),
        ),
    ]
