# Generated by Django 6.0.3 on 2026-03-20 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0009_owners_only_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='expense_category',
            field=models.CharField(choices=[('gardener', 'Κηπουρός'), ('common_power_usage', 'Κοινόχρηστο ρεύμα'), ('common_water_usage', 'Κοινόχρηστο νερό'), ('cleaning', 'Καθαρισμός'), ('elevator_service', 'Συντήρηση ανελκυστήρα'), ('gas_heating_bill', 'Φυσικό αερίο θέρμανσης'), ('water_hw_consumption_bill', 'Κατανάλωση ζεστού νερού'), ('gas_hw_consumption_bill', 'Φυσικο αέριο ζεστού νερού'), ('damages', 'Ζημιές'), ('annual_servicing', 'Ετήσια συντήρηση'), ('owners_only', 'Έξοδα μόνο ιδιοκτητών'), ('other', 'Λοιπά')], max_length=64),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική μεταφορά'), ('card', 'Κάρτα'), ('other', 'Άλλο')], default='bank_transfer', max_length=32)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='flats.apartment')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='flats.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('receipt_paid', 'Απόδειξη εξόφλησης')], max_length=32)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Σε αναμονή'), ('sent', 'Εστάλη'), ('failed', 'Απέτυχε'), ('skipped', 'Παραλείφθηκε')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to='flats.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to='flats.paymentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Τιμολόγιο'), ('receipt', 'Απόδειξη πληρωμής')], max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=127)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='flats.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='flats.paymentrecord')),
            ],
        ),
    ]
