# Generated by Django 6.0.3 on 2026-03-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0010_alter_expenseitem_expense_category_paymentrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdispatch",
            name="notification_type",
            field=models.CharField(
                choices=[("receipt_paid", "Απόδειξη εξόφλησης"), ("invoice_monthly", "Μηνιαία αποστολή λογαριασμού")],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="VoteSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_type",
                    models.CharField(
                        choices=[("administrator_election", "Εκλογή διαχειριστή"), ("motion", "Θέμα ψηφοφορίας")],
                        default="motion",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Πρόχειρη"), ("active", "Ενεργή"), ("closed", "Κλειστή")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vote_sessions", to="flats.building"),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vote_value", models.CharField(choices=[("yes", "Ναι"), ("no", "Όχι"), ("abstain", "Αποχή")], max_length=16)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apartment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="flats.apartment"),
                ),
                (
                    "vote_session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="flats.votesession"),
                ),
                (
                    "voter_user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(fields=("vote_session", "apartment"), name="uniq_vote_session_apartment"),
        ),
    ]
