# Generated by Django 6.0.3 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0011_alter_notificationdispatch_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="votesession",
            name="vote_options_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote_value",
            field=models.CharField(max_length=64),
        ),
    ]
