# Generated by Django 6.0.3 on 2026-06-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0012_votesession_vote_options_json_alter_vote_vote_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatedwatermeasurementinput',
            name='billing_period_end',
        ),
        migrations.RemoveField(
            model_name='heatedwatermeasurementinput',
            name='billing_period_start',
        ),
        migrations.RemoveField(
            model_name='heatingmeasurementinput',
            name='billing_period_end',
        ),
        migrations.RemoveField(
            model_name='heatingmeasurementinput',
            name='billing_period_start',
        ),
    ]
