# Generated by Django 6.0.3 on 2026-06-10 23:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0013_remove_heatedwatermeasurementinput_billing_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='fund_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='apartmentuser',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='User is recorded as owner of this apartment.'),
        ),
        migrations.AlterField(
            model_name='apartmentuser',
            name='is_tenant',
            field=models.BooleanField(default=True, help_text='User has access as a resident (tenant) of this apartment.'),
        ),
    ]
