# Generated by Django 6.0.3 on 2026-06-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0014_building_fund_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='expense_category',
            field=models.CharField(choices=[('gardener', 'Κηπουρός'), ('common_power_usage', 'Κοινόχρηστο ρεύμα'), ('common_water_usage', 'Κοινόχρηστο νερό'), ('cleaning', 'Καθαρισμός'), ('elevator_service', 'Συντήρηση ανελκυστήρα'), ('gas_heating_bill', 'Φυσικό αερίο θέρμανσης'), ('water_hw_consumption_bill', 'Κατανάλωση ζεστού νερού'), ('gas_hw_consumption_bill', 'Φυσικο αέριο ζεστού νερού'), ('damages', 'Ζημιές'), ('annual_servicing', 'Ετήσια συντήρηση'), ('owners_only', 'Έξοδα μόνο ιδιοκτητών'), ('fund_increase', 'Αύξηση αποθεματικού'), ('other', 'Λοιπά')], max_length=64),
        ),
    ]
